---
- name: Create Local Admin Users
  ansible.windows.win_user: 
    name: "{{ item }}"
    password: "{{ win_team_password }}"
    state: present
    update_password: always
    groups_action: add
    groups: 
      - Users
      - Administrators
      - Remote Management Users
  loop:
    - orange

- name: Add Local Users
  ansible.windows.win_user:
    name: "{{ users }}"
    password: "{{  win_team_password }}"
    state: present
    update_password: always 
    groups_action: add
    groups: 
      - Users
      - Remote Management Users
  loop: 
    - green
    - cyan
    - vent 
    - brown
    - yellow
    - lime