---
# ansible variables
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
become_method: runas
ansible_become_user: "GrayTeam"
ansible_become_password: "admin123!"

## Windows
win_team_password: "{{ team_password }}"
domain_netbios_name: "team{{ team_number }}"
dc_domain_name: "{{ inventory_hostname | replace(inventory_hostname_short, '') | replace('.', '', 1) }}"
domain_user:  "Administrator@{{ dc_domain_name }}"

safe_mode_password: "{{ win_team_password }}"
primary_dns_server: 127.0.0.1
secondary_dns_server: 8.8.8.8
