---
- name: Install Sysinternals
  chocolatey.chocolatey.win_chocolatey:
    name: sysinternals
    version: '2022.1.27'
    params: /InstallDir:C:\Users\Public\Desktop\sysinternals
    state: present