---
# icmp and rdp should go in this role 
- name: Run on all Windows Boxes
  hosts: windows
  roles: 
    - windows_deploy_all
    - windows_deploy_rdp
    - windows_deploy_icmp 

- name: Install Windows Tools 
  hosts: windows
  roles: 
    - windows_install_tools

- name: Configure AD/DNS
  hosts: reactor
  roles: 
    - windows_deploy_dns
    - windows_deploy_dc

- name: Join Windows boxes to Domain 
  hosts: windows:!reactor
  roles: 
    - windows_join_domain

- name: Create Local Users
  hosts: windows
  roles: 
    - windows_create_local_users

- name: Create SMB Share
  hosts: shields
  roles: 
    - windows_deploy_smb    

- name: Change Hostname (Linux)
  hosts: linux
  roles: 
    - linux_set_hostname

- name: Create FTP (Linux)
  hosts: medbay
  roles:
    - linux_deploy_ftp

- name: Create HTTP (Linux)
  hosts: electrical
  roles:
    - linux_deploy_http

- name: Create Linux Users
  hosts: linux
  roles:
    - linux_create_users
