---
#Part of DC prereq - setting administrator password
- name: Set Administrator Password
  win_user:
    name: Administrator
    password: '{{ win_team_password }}'
    state: present
  ignore_errors: True

- name: Install Active Directory
  ansible.windows.win_feature: 
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present
  register: ad_install

- name: Prevent WinRM Connections Until Installation is Finished
  ansible.windows.win_service:
    name: WinRM
    start_mode: delayed

- name: Restart if Needed
  ansible.windows.win_reboot:
  when: ad_install.reboot_required